server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://core:8000/   # имя контейнера
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-core
            - JwtAuthFilter
        - id: cart-service
          uri: http://cart:8166/    # имя контейнера
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-cart
            - JwtAuthFilter
        - id: user-service
          uri: http://user:8188/    # имя контейнера
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-user
            - JwtAuthFilter

jwt:
  secret: aevsggrixfnfgkrgnjfshgeilgskdfnvsjbvlkghri

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka/}
    fetch-registry: false