eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka/}
spring:
  config:
    import: optional:configserver:lb://config-service/
  profiles:
    active: ${SPRING_PROFILES_INCLUDE:dev}
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
      label: ${SPRING_CLOUD_CONFIG_LABEL:main}
      username: ${SPRING_CLOUD_CONFIG_USERNAME:nhp-user} # Для входа в config-service
      password: ${SPRING_CLOUD_CONFIG_PASSWORD:nhp-pass}
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
            - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: lb://core-service/   # имя приложения в eureka
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-core
            - JwtAuthFilter
        - id: cart-service
          uri: lb://cart-service/    # имя приложения в eureka
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-cart
            - JwtAuthFilter
        - id: user-service
          uri: lb://user-service/    # имя приложения в eureka
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-user
            - JwtAuthFilter
        - id: analytics-service
          uri: lb://analytics-service/    # имя приложения в eureka
          predicates:
            - Path=/analytics/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-analytics
            - JwtAuthFilter