server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://core:8000/   # имя контейнера
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-core
            - JwtAuthFilter
        - id: cart-service
          uri: http://cart:8166/    # имя контейнера
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/web-market-carts
            - JwtAuthFilter

jwt:
  secret: vRGktmhw54y93i9jstt@#O@oyjth

