server:
  port: 8166
  servlet:
    context-path: /web-market-cart
utils:
  cart:
    prefix: SPRING_WEB_APP_
integrations:
  core-service:
    url: http://localhost:5555/core
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka/}
    fetch-registry: false
spring:
  application:
    name: cart-service