server:
  port: 8189
  servlet:
    context-path: /web-market-analytics
utils:
  cart:
    prefix: SPRING_WEB_APP_
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5   # интервал сигналов на сервер eureka
    lease-expiration-duration-in-seconds: 10 # таймер "down" после последнего сигнала
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka/}
    registerWithEureka: true
    fetchRegistry: true
    registry-fetch-interval-seconds: 5 #  интервал извлечения информации о регистрации сервисов
spring:
  application:
    name: analytics-service
