server:
  port: 8000
  servlet:
    context-path: /web-market-core
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5430/beta
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: core-service
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
integrations:
  cart-service:
    url: lb://gateway:5555/cart  #  имя контейнера в docker
    connect-timeout: 2000
    read-timeout: 10000
    write-timeout: 2000
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka/}
    registerWithEureka: true
    fetchRegistry: true