eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka/}
spring:
  config:
    import: optional:configserver:lb://config-service/
  application:
    name: core-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service