server:
  port: ${PORT:8888}
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka/}
    registerWithEureka: true
    fetchRegistry: true
spring:
  application:
    name: config-service
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: ${GIT_URI:https://github.com/NHP22/nhp-settings}
          search-paths: ${GIT_SEARCH_PATHS:/nhp-configs}  # путь внутри репозитория
          clone-on-start: true   # при старте config-service из репозитория подтягиваются изменения
          username: ${GIT_USERNAME:NHP22}  # имя репозитория
          password: ${GIT_PASSWORD:NhP_2022}  # пароль репозитория
        default-label: main  # ветка в репозитории по умолчанию
        default-profile: dev # профиль по умолчанию

        # localhost:8888/{application_name}/{profile}/{label}
        # localhost:8888/core-service/dev/main
